title: retinify documentation
description: Documentation for the retinify project.
theme: just-the-docs

url: https://retinify.github.io/retinify-documentation/

aux_links:
  retinify Repository: https://github.com/retinify/retinify